// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shoko.Plugin.Tvdb.Storage;

#nullable disable

namespace Shoko.Plugin.Tvdb.Storage.Migrations
{
    [DbContext(typeof(TvdbDbContext))]
    partial class TvdbDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Shoko.Plugin.Tvdb.Storage.TvdbStoredPerson", b =>
                {
                    b.Property<int>("ID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Birth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Death")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Found")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .HasColumnType("TEXT");

                    b.ComplexCollection(typeof(List<Dictionary<string, object>>), "Biographies", "Shoko.Plugin.Tvdb.Storage.TvdbStoredPerson.Biographies#TvdbStoredText", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Language");

                            b1.Property<string>("Value")
                                .IsRequired();

                            b1
                                .ToJson("Biographies")
                                .HasColumnType("TEXT");
                        });

                    b.ComplexCollection(typeof(List<Dictionary<string, object>>), "Names", "Shoko.Plugin.Tvdb.Storage.TvdbStoredPerson.Names#TvdbStoredText", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Language");

                            b1.Property<string>("Value")
                                .IsRequired();

                            b1
                                .ToJson("Names")
                                .HasColumnType("TEXT");
                        });

                    b.ComplexCollection(typeof(List<Dictionary<string, object>>), "RemoteIDs", "Shoko.Plugin.Tvdb.Storage.TvdbStoredPerson.RemoteIDs#TvdbStoredRemoteID", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("ID")
                                .IsRequired();

                            b1.Property<string>("SourceName");

                            b1.Property<int?>("Type");

                            b1
                                .ToJson("RemoteIDs")
                                .HasColumnType("TEXT");
                        });

                    b.HasKey("ID");

                    b.ToTable("People", (string)null);
                });

            modelBuilder.Entity("Shoko.Plugin.Tvdb.Storage.TvdbStoredPortrait", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("Portraits", (string)null);
                });

            modelBuilder.Entity("Shoko.Plugin.Tvdb.Storage.TvdbStoredSeries", b =>
                {
                    b.Property<int>("ID")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("AlternateSeasonTypes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EpisodeThumbnails")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Poster")
                        .HasColumnType("TEXT");

                    b.Property<string>("SeasonPosters")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SeasonType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.ComplexCollection(typeof(List<Dictionary<string, object>>), "Artworks", "Shoko.Plugin.Tvdb.Storage.TvdbStoredSeries.Artworks#TvdbStoredArtwork", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int?>("Height");

                            b1.Property<int>("ID");

                            b1.Property<string>("Language");

                            b1.Property<string>("Path")
                                .IsRequired();

                            b1.Property<int?>("SeasonID");

                            b1.Property<int>("Type");

                            b1.Property<int?>("Width");

                            b1
                                .ToJson("Artworks")
                                .HasColumnType("TEXT");
                        });

                    b.HasKey("ID");

                    b.ToTable("Shows", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
